# Generated by Django 3.1.7 on 2021-03-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='finish',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
    ]
