# Generated by Django 3.1.7 on 2021-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210331_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
