# Generated by Django 3.1.7 on 2021-04-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210331_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='finish',
            field=models.CharField(max_length=5),
        ),
    ]
