# Generated by Django 3.1.7 on 2021-04-03 03:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_activities_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='Dates',
            field=models.DateField(default=datetime.datetime(2021, 4, 3, 3, 9, 48, 658761, tzinfo=utc), max_length=60),
            preserve_default=False,
        ),
    ]
